version: 0.2

phases:
  build:
    commands:
      - echo nothing to do yet
artifacts:
  files:
    - index.html
    - images/favicon.icon
    - ArunKPGopal2017.pdf
    - styles/main.css
    - images/*
